server:
  port: 8989
spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:5544
  datasource:
    url: jdbc:h2:mem:eco-db
  h2:
    console:
      enabled: true
